name: habitat
channels:
  - aihabitat
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9

  # System-level dependencies that work better with conda
  - cmake
  - git
  - git-lfs

  # Habitat-sim specific conda packages (required from aihabitat channel)
  - habitat-sim-mutex=1.0=display_bullet
  - withbullet=2.0=0

  # Install everything else via pip
  - pip
  - pip:
    - -r requirements.txt