defaults:
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - move_forward
    - turn_left
    - turn_right
    - answer
  - /habitat/task/measurements:
    - episode_info
    - answer_accuracy
  - /habitat/task/lab_sensors:
    - question_sensor
  - _self_

type: EQA-v0