# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: HM3DExpress-v1
split: train
data_path: data/datasets/eqa/hm3d/express-bench/express-bench.json
scenes_dir: data/scene_datasets/